CRITICAL - 2024-05-14 15:18:36 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 219)
#1 C:\xampp\htdocs\cubicaje\app\Controllers\Usuarios.php(219): mail('usuario', 'Recuperar contr...', 'Para recuperar ...', 'From: cristobap...')
#2 C:\xampp\htdocs\cubicaje\system\CodeIgniter.php(832): App\Controllers\Usuarios->recovery()
#3 C:\xampp\htdocs\cubicaje\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#4 C:\xampp\htdocs\cubicaje\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\cubicaje\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2024-05-14 15:25:13 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 219)
#1 C:\xampp\htdocs\cubicaje\app\Controllers\Usuarios.php(219): mail('usuario', 'Recuperar contr...', 'Para recuperar ...', 'From: cristobap...')
#2 C:\xampp\htdocs\cubicaje\system\CodeIgniter.php(832): App\Controllers\Usuarios->recovery()
#3 C:\xampp\htdocs\cubicaje\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#4 C:\xampp\htdocs\cubicaje\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\cubicaje\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2024-05-14 15:28:13 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 219)
#1 C:\xampp\htdocs\cubicaje\app\Controllers\Usuarios.php(219): mail('usuario', 'Recuperar contr...', 'Para recuperar ...', 'From: cristobap...')
#2 C:\xampp\htdocs\cubicaje\system\CodeIgniter.php(832): App\Controllers\Usuarios->recovery()
#3 C:\xampp\htdocs\cubicaje\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#4 C:\xampp\htdocs\cubicaje\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\cubicaje\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2024-05-14 15:29:08 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 219)
#1 C:\xampp\htdocs\cubicaje\app\Controllers\Usuarios.php(219): mail('usuario', 'Recuperar contr...', 'Para recuperar ...', 'From: cristobap...')
#2 C:\xampp\htdocs\cubicaje\system\CodeIgniter.php(832): App\Controllers\Usuarios->recovery()
#3 C:\xampp\htdocs\cubicaje\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#4 C:\xampp\htdocs\cubicaje\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\cubicaje\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2024-05-14 15:29:52 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 219)
#1 C:\xampp\htdocs\cubicaje\app\Controllers\Usuarios.php(219): mail('usuario', 'Recuperar contr...', 'Para recuperar ...', 'From: cristobap...')
#2 C:\xampp\htdocs\cubicaje\system\CodeIgniter.php(832): App\Controllers\Usuarios->recovery()
#3 C:\xampp\htdocs\cubicaje\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#4 C:\xampp\htdocs\cubicaje\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\cubicaje\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2024-05-14 15:30:48 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 219)
#1 C:\xampp\htdocs\cubicaje\app\Controllers\Usuarios.php(219): mail('usuario', 'Recuperar contr...', 'Para recuperar ...', 'From: cristobap...')
#2 C:\xampp\htdocs\cubicaje\system\CodeIgniter.php(832): App\Controllers\Usuarios->recovery()
#3 C:\xampp\htdocs\cubicaje\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#4 C:\xampp\htdocs\cubicaje\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\cubicaje\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2024-05-14 15:31:56 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 219)
#1 C:\xampp\htdocs\cubicaje\app\Controllers\Usuarios.php(219): mail('usuario', 'Recuperar contr...', 'Para recuperar ...', 'From: cristobap...')
#2 C:\xampp\htdocs\cubicaje\system\CodeIgniter.php(832): App\Controllers\Usuarios->recovery()
#3 C:\xampp\htdocs\cubicaje\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#4 C:\xampp\htdocs\cubicaje\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\cubicaje\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2024-05-14 15:32:29 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 219)
#1 C:\xampp\htdocs\cubicaje\app\Controllers\Usuarios.php(219): mail('usuario', 'Recuperar contr...', 'Para recuperar ...', 'From: cristobap...')
#2 C:\xampp\htdocs\cubicaje\system\CodeIgniter.php(832): App\Controllers\Usuarios->recovery()
#3 C:\xampp\htdocs\cubicaje\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#4 C:\xampp\htdocs\cubicaje\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\cubicaje\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2024-05-14 15:33:07 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 219)
#1 C:\xampp\htdocs\cubicaje\app\Controllers\Usuarios.php(219): mail('usuario', 'Recuperar contr...', 'Para recuperar ...', 'From: cristobap...')
#2 C:\xampp\htdocs\cubicaje\system\CodeIgniter.php(832): App\Controllers\Usuarios->recovery()
#3 C:\xampp\htdocs\cubicaje\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#4 C:\xampp\htdocs\cubicaje\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\cubicaje\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2024-05-14 15:33:51 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 219)
#1 C:\xampp\htdocs\cubicaje\app\Controllers\Usuarios.php(219): mail('usuario', 'Recuperar contr...', 'Para recuperar ...', 'From: cristobap...')
#2 C:\xampp\htdocs\cubicaje\system\CodeIgniter.php(832): App\Controllers\Usuarios->recovery()
#3 C:\xampp\htdocs\cubicaje\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#4 C:\xampp\htdocs\cubicaje\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\cubicaje\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2024-05-14 15:58:20 --> mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 219)
#1 C:\xampp\htdocs\cubicaje\app\Controllers\Usuarios.php(219): mail('usuario', 'Recuperar contr...', 'Para recuperar ...', 'From: cristobap...')
#2 C:\xampp\htdocs\cubicaje\system\CodeIgniter.php(832): App\Controllers\Usuarios->recovery()
#3 C:\xampp\htdocs\cubicaje\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#4 C:\xampp\htdocs\cubicaje\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\cubicaje\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
